### ISSUE TITLE
Migration does not append correct has_m option to schema.rb

### ISSUE THREAD

**Issue by eidge** [rgeo/activerecord-postgis-adapter#101]
Take the following migration:

```
create_table "city_borders", force: true do |t| 
  t.spatial  "geom", limit: {:srid=>4326, :type=>"line_string", :has_z=>true, :has_m=>true}
end
```

The following schema will be generated:

```
create_table "city_borders", force: true do |t| 
  t.spatial  "geom", limit: {:srid=>4326, :type=>"line_string", :has_z=>true}
end
```

**Missing the has_m option** and therefore breaking all the subsequent migrations or schema:load's.

I'm using:
**ruby 2.0.0**
**rails 4.0.2**
*_activerecord-postgis-adapter '~>0.6.5' *_

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
