### ISSUE TITLE
Rails 4.0+ support

### ISSUE THREAD

**Issue by teeparham** [rgeo/activerecord-postgis-adapter#107]
_UPDATE: Rails 4 support is done. I am the new maintainer of this project._

Version 1.1 and later supports PostGIS 2.0+ & Rails 4.x (only): 

Rails 4.0 & 4.1:

```
gem 'activerecord-postgis-adapter'
```

There is no JRuby support for Rails 4 yet.

**Comment by ddd1600** [comment]
make sure your `adapter` in `config/database.yml` is set to "postgis".
