### ISSUE TITLE
Column has srid but geometry does not

### ISSUE THREAD

**Issue by ldonnet** [rgeo/activerecord-postgis-adapter#109]
I'm using Rails 4,  Ruby 1.9.3, Postgres 9.3 and Postgis 2.1. 
When a point is defined as:

``` ruby
t.point :point, :srid => 4326
```

And my factory as : 

``` ruby
RGeo::Geos.factory(:native_interface => :ffi, :srid => 4326,
                                               :wkt_parser => {:support_ewkt => true, :default_srid => 4326},
                                               :wkt_generator => {:tag_format => :ewkt, :emit_ewkt_srid => true},
                                               :wkb_parser => {:support_ewkb => true, :default_srid => 4326},
                                               :wkb_generator => {:type_format => :ewkb, :emit_ewkt_srid => true}
                                               )
```

When I save my point in a model Location in ActiveRecord, I got the good srid with : Location.geometry.srid. But when I want to get my geometry from ActiveRecord srid seems disappear : 

``` ruby
Location.geometry
=> #<RGeo::Geos::FFIPointImpl:0x2efa2e8 "POINT (0.1 0.82)">
Location.geometry.as_text
=> "POINT (0.1 0.82)"
```

Does anyone have a clue?

**Comment by turboladen** [comment]
I'm not super familiar with RGeo, but IIRC, the coordinate system/spatial reference/srid is stored at the layer level (thus all features and geometries within that layer are relative to such). I'd guess `Location.geometry.srid` would just be a convenience method that pulls the srid from the layer, thus if you dumped the whole layer from PostGIS, you'd get the srid as part of that layer, but it wouldn't be at the geometry level.  Not sure if that makes any sense...

**Comment by pichot** [comment]
Any updates on this? I'm encountering the same issue.

**Comment by mjy** [comment]
@keithdoggett this seems to be an issue with Rgeo, not the adapter?  Suggestion to close it here and re-open in Rgeo if still issue?
