### ISSUE TITLE
2.0.x new way to deal with schema breaks multi-schema apps

### ISSUE THREAD

**Issue by kaligrafy** [rgeo/activerecord-postgis-adapter#115]
I have a rails app that uses multiple schemas: schema_search_path: "rails, datawarehouse, public"

I want postgis to use the public schema. With versions 1.x of activerecord-postgis-adapter, it worked well (postgis went to the public schema, and all my other tables were sent to rails or datawarehouse schemas according to a parameter in my migrations files.

Now, with version 2.0.x, only the public schema is created and the other two are ignored (not created), so all my tables go to the public schema when migrating.

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
