### ISSUE TITLE
Rails Console Production Env - NoMethodError: undefined method `point'

### ISSUE THREAD

**Issue by ahallock** [rgeo/activerecord-postgis-adapter#120]
Setup:
Rails 4.0.2
activerecord-postgis-adapter 2.0.1
Ruby 2.1

Command:
`RAILS_ENV=production rails c`

Error occurs here:
`Place.rgeo_factory_for_column(:coords).point(longitude, latitude)`

Place.rb:

``` ruby
class Place < ActiveRecord::Base
    set_rgeo_factory_for_column(:coords, RGeo::Geographic.spherical_factory(srid: 4326))
```

This error does not occur in the development environment. Both envs use the `postgis` adapter in `database.yml`

**Comment by lessless** [comment]
Same issue with `activerecord-postgis-adapter 3.1.4`  with rails 4.2.4

**Comment by archfish** [comment]
[see this](https://github.com/rgeo/activerecord-postgis-adapter/issues/195) they are same

**Comment by mjy** [comment]
@keithdoggett close as dupe?
