### ISSUE TITLE
Incompatibility with schema_plus due to SpatialIndexDefinition

### ISSUE THREAD

**Issue by bill-myers** [rgeo/activerecord-postgis-adapter#141]
This gem is currently incompatible with schema_plus because it uses SpatialIndexDefinition from RGeo, while schema_plus expects to see a version of ActiveRecord's IndexDefinition monkey-patched by itself.

As a result, schema_plus crashes when trying to access its own added properties to the index.

I'd suggest to revert to using the default ActiveRecord's IndexDefinition and to change rgeo-activerecord to monkey patch IndexDefinition by adding an "attr_accessor :spatial" or equivalent code instead of defining SpatialIndexDefinition.

**Comment by phlegx** [comment]
I have the same problem but this solution don't work for me :(

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
