### ISSUE TITLE
Unknown key: :case_sensitive

### ISSUE THREAD

**Issue by phlegx** [rgeo/activerecord-postgis-adapter#146]
**Rails:** 4.1
**DB:** PostgreSQL 9.3
**Adapter:** Activerecord PostGis Adapter 2.2.1

In my `database.yml` I use this here (required adapter for PostGis):

``` yaml
development:
  adapter: postgis
  ...
```

My migration:

``` ruby
...
  def self.up
    change_table :users do |t|
      t.string :email
  end

  add_index :accounts, :email, unique: true, case_sensitive: false
...
```

Any idea how to solve this problem? Is this a activerecord-postgis-adapter issue?

**Comment by mjy** [comment]
@keithdoggett I suspect can be closed as unrelated, this is core, not postgis?  

FYI See https://stackoverflow.com/questions/7948501/case-insensitive-unique-index-in-rails-activerecord
