### ISSUE TITLE
doesn't support ActiveRecord::AttributeMethods::Serialization

### ISSUE THREAD

**Issue by ericcj** [rgeo/activerecord-postgis-adapter#149]
I'm working with a projected geometry column in the database (to leverage postgresql's nearest neighbor <-> operator) that I only want to actually use as spherical coordinates in my app. I initially overwrote the getter/setter methods in my model as a lot of blog posts suggest, but quickly realized that we access/update this field using subscript operators, the #update method, etc. that don't go through those.  ActiveRecord's serialize method seemed like a good choice to isolate this concern:  http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize using a simple custom coder class that did:

```
def self.load(serialized)
  GEOFACTORY.unproject(serialized)
end

def self.dump(value)
  GEOFACTORY.project(value)
end
```

Unfortunately, activerecord-postgis-adapter doesn't seem to support this since DecorateColumnsModification#decorate_columns doesn't expect to receive a ActiveRecord::AttributeMethods::Serialization::Type and therefore the column is left as a raw SpatialOID instead of replaced with the "canonical" SpatialColumn.  If I fix that, though, SpatialColumn#type_cast doesn't expect to receive a ActiveRecord::AttributeMethods::Serialization::Attribute and therefore returns nil.  

If I leave it broken (using SpatialOID instead of the column), all I have to work around is that SpatialOID type_cast's by parsing WKB and rescuing nil (which seems worse than failing fast) and that fails since the serialized value is a geometry and not WKB string.  That's easily fixed by dumping to a WKB string from my coder but doesn't seem to be the intended flow of things.  Does anyone have any suggestions of how this should work?  Perhaps it's more easily doable in https://github.com/rgeo/activerecord-postgis-adapter/pull/145 since rails 4.2 refactored serialization a bit?

**Comment by keithdoggett** [comment]
I was able to get this to work on version 6.0.1. If this is still an issue please re-open.
