### ISSUE TITLE
Few Incompatible column types in gem with Rails 4.1.x

### ISSUE THREAD

**Issue by ishwinder** [rgeo/activerecord-postgis-adapter#151]
ActiveRecord 4.1.7
activerecord-postgis-adapter latest version.

The database structure is like:
address:string
longlat: point

A simple save to the spatial datatype returns an incompatible format error

ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type point: "0020000001000010e6403cb91148fd9fd3405347e657b84dba"

Seems like activerecord-postgis-adapter is trying to convert to binary before firing the insert query.

The code is simple:

``` Ruby
l = Location.new
l.longlat = 'POINT(28.72292 77.123434)'
l.address = "My Address"
l.save
```

and on console RGeo::Geos.supported? returns true.

Now, the same code works if the column long lat is of the type geometry, so the incompatibility seems to be with few column types only.

**Comment by iurifq** [comment]
I'm using rails 4.1.10 and I hit on a similar error. I could fix it, but I'm still not sure of how. I didn't change anything in the code, but I reinstalled postgis, rolled back and migrated the relevant migrations. That means that my case was just a database configuration problem, not a problem in the gem itself. Maybe it's the same here.

**Comment by dcdieci** [comment]
I just added
   t.point :lonlat, :srid => 4326, :type => "point", :geographic => true
to the migration and it worked

**Comment by mjy** [comment]
@keithdoggett I suspect we can close.
