### ISSUE TITLE
Support for 'multi' geometries

### ISSUE THREAD

**Issue by djantzen** [rgeo/activerecord-postgis-adapter#157]
Hi Tee,

This looks like a great tool, although it doesn't appear to handle things like multipolygons. Is that on the roadmap at all?

Thanks,
David

**Comment by mjy** [comment]
We've have a multi-polygon column using it, though maybe I'm missing
something.

**Comment by djantzen** [comment]
Sorry I should have been more specific. It appears the migration DSL only supports single geometries like 'polygon'. I tried to do an add_column operation with 'multipolygon' and it failed.

**Comment by mjy** [comment]
A rails migration:

    add_column :geographic_items, :multi_polygon, :multi_polygon,
:geographic => true, :has_z => true, :has_m => true

**Comment by djantzen** [comment]
Well that would be user error. Thanks for setting me straight.

**Comment by teeparham** [comment]
Thanks @mjy!
