### ISSUE TITLE
Document how to configure Rails app when you can't have superuser credentials in database.yml

### ISSUE THREAD

**Issue by sauy7** [rgeo/activerecord-postgis-adapter#159]
I'd like to propose adding a few sentences to the project README explaining how to configure a Rails application when you are not able to specify superuser credentials in database.yml (even if your database.yml uses environment variables).

I've just discovered this is the case for deploying to AWS on Engine Yard. EY, sensibly, wish to protect superuser credentials from application-level users, so the postgres user's password is not available (not even as an environment variable).

The project README recommends adding su_username, su_password and implicitly use Rails default migrations (schema.rb).

This is not possible on Engine Yard. The solution is to install the postgis extension via a custom chef recipe and configure the Rails application to generate sql-formatted migrations with this line added to config/application.rb:

```
config.active_record.schema_format = :sql
```

I guess there is a general rule that if you are using database-specific code in a Rails app, you should use sql formatted schemas instead of the AR schema dumper, but having this clearly explained here too might help others.

**Comment by joeytheman** [comment]
How are you trying to set things up?

I deploy to Engine Yard with the actievrecord-postgis-adapter without problems.  I enabled postgis on my database using the following migration

enable_postgis.rb

````ruby
class EnablePostgis < ActiveRecord::Migration
  def change
    enable_extension :postgis
  end
end
````

and I add `adapter: postgis` to my  `config/database.yml` in a `before_restart.rb` deploy hook.

**Comment by sauy7** [comment]
Postgis is installed via the custom chef recipe here: https://github.com/engineyard/ey-cloud-recipes/tree/master/cookbooks/postgresql9_extensions

database.yml is maintained with postgis settings in a keep file: /data/<app_name>/shared/config/keep.database.yml as per this page: https://support.cloud.engineyard.com/entries/20996641-Use-Keep-Files-to-Customize-and-Maintain-Configurations

@joeytheman I was not able to use schema.rb with the same migration as you to enable the extension because the user specified in the database.yml is not a superuser (for the reasons I explained above). Do you have a superuser specified in your database.yml? I believe you need that for the enable_extension command to run. If not, what EY stack version are you running? Maybe something has changed - I'm running stable-v4 2.0.

**Comment by mjy** [comment]
@keithdoggett not sure what to do with issues like this, seems they are not related to the adapter, suggestion would be to close as expired/unrelated to keep focus on important issues?

**Comment by sauy7** [comment]
Feel free to close.

**Comment by keithdoggett** [comment]
@mjy I agree. We can always use this as a reference if we need to add documentation about it in the future.

Thanks for going through and tagging all these issues!
