### ISSUE TITLE
When running migrations the spatial column is being created with incorrect name

### ISSUE THREAD

**Issue by desaperados** [rgeo/activerecord-postgis-adapter#168]
3.0.0.beta2

Looks like the migration api is broken somewhere. The following migration

```ruby
create_table :features, id: :uuid do |t|
  t.geometry :the_geom, srid: 4326
end
```

Results in this in the schema:

```ruby
create_table "features", id: :uuid, force: :cascade do |t|
  t.geometry "{:limit=>{:srid=>3857, :type=>\"geometry\"}}", limit: {:srid=>0, :type=>"geometry"}
end
```

**Comment by teeparham** [comment]
That looks bad. Thanks for reporting. This may be the culprit: https://github.com/rgeo/activerecord-postgis-adapter/commit/e615a05983b6

Does it work in 3.0.0.beta1?

**Comment by desaperados** [comment]
Sorry I haven't tried with beta1 - we've been using db:schema:load since upgrading to Rails 4.2 to avoid any issues. This is our first attempt at updating migrations for the new api

**Comment by teeparham** [comment]
I added a test and updated an existing test to try to reproduce the problem in https://github.com/rgeo/activerecord-postgis-adapter/commit/5ac8fb5ac94f1460, but I could not reproduce it.

**Comment by desaperados** [comment]
Thanks - I've just tried and been unable to reproduce with a brand new Rails application. The issue is still showing in the working application but must be application specific.

**Comment by teeparham** [comment]
It's possible that the schema dump changed, so you would need to run `rake db:schema:dump` on an existing project after upgrading to 3.0.0 & before running additional migrations.
