### ISSUE TITLE
data types - no st_point, only point

### ISSUE THREAD

**Issue by agoddard** [rgeo/activerecord-postgis-adapter#169]
Hi, I'm brand new to this adaptor, so I might be getting something wrong - but it appears when you use the `st_point` data type for a column in a migration, the migration throws an ```undefined method``` error for `st_point`, but `point` works just fine. Is the correct data type for a point now `point` and the docs are outdated, or are `point` and `st_point` distinct data types?

**Comment by mjy** [comment]
2.n uses point
3.beta use st_point.  To get st_point you have to update your gemfile to
reference the current beta.

In other words, yes, docs will need updating.

M

**Comment by agoddard** [comment]
awesome, makes perfect sense now, thanks!
