### ISSUE TITLE
RGeo::Error::UnsupportedOperation: Method Surface#centroid not defined

### ISSUE THREAD

**Issue by revans** [rgeo/activerecord-postgis-adapter#173]
It seems with the latest beta version (3.0.0.beta2) that getting the centroid of a shape is not currently supported?

```
irb(main):005:0> d = _

#<Polygon id: 232, hole_id: 19, polygon_type_id: 4, label: nil, shape: #<RGeo::Geographic::SphericalPolygonImpl:0x3ff1f21046a8 "POLYGON ((-117.28641271591187 33.14883200578226, -117.28641808032988 33.148807303216365, -117.28641808032988 33.148780354954724, -117.28640466928482 33.14875789806368, -117.2863644361496 33.14873768685683, -117.28631883859634 33.148735441166885, -117.28625714778899 33.148733195476915, -117.28623569011688 33.148751160995246, -117.2862383723259 33.148773617888, -117.28624641895294 33.1488050575282, -117.28627055883409 33.14882526871953, -117.2862920165062 33.14883200578226, -117.28633493185043 33.14883200578226, -117.28637248277664 33.14883425146974, -117.28641271591187 33.14883200578226))">, position: 2, created_at: "2014-06-04 18:53:18", updated_at: "2015-03-16 22:23:05">

irb(main):006:0> d.shape.centroid
RGeo::Error::UnsupportedOperation: Method Surface#centroid not defined.

```

Is this something that isn't in yet or has changed?

**Comment by seuros** [comment]
seem like Geos is not installed in your machine.

**Comment by revans** [comment]
I have it installed. (v3.4.2). In irb, doing RGeo::Geos.supported? returns true. e.g.

````
require 'rgeo'
=> true
RGeo::Geos.supported?
=> true
````

**Comment by drewda** [comment]
I'm getting the same error as @revans with:

* activerecord-postgis-adapter 3.0.0.beta2
* Rails 4.2.0
* Ruby 2.1.3p242

And in the Rails console, I also see:

````
[1] pry(main)> RGeo::Geos.supported?
=> true
````

**Comment by revans** [comment]
I'll have some time next week to try and figure this out.

**Comment by sauy7** [comment]
I'm not really very conversant with the internals of the family of Rgeo gems but I think this is really an issue with the rgeo gem, not this adapter.

Looking in the source of that gem it appears that the centroid method (one of many) is only implemented for Rgeo::Geographic::ProjectedPolygonImpl and not Rgeo::Geographic::SphericalPolygonImpl.

I'm not sure why this is. I've wanted to use "intersects?" on a SphericalGeometryCollectionImpl but it is only implemented for ProjectedGeometryCollectionImpl. I can run the ST_Intersects function on the geometry collection fields I have in the database, so maybe I'm misunderstanding how rgeo factories can be used in AR models?

Hopefully someone with more knowledge of Rgeo can chip in here?

**Comment by sauy7** [comment]
I found this comment from @dazuma on the rgeo-users mailing list:

"Some operations, including centroid, are available only under the following conditions: 
* You are using a cartesian (i.e. projected) coordinate system. Thus, simple_spherical will not support it. 
* You have GEOS available (that is, RGeo::Geos.supported? returns true) 
Which factory are you using, and do you have Geos installed?"

See: https://groups.google.com/forum/#!topic/rgeo-users/WAqzmG0IvbM

This would explain your centroid issue but does not explain why:
    ```boolean ST_Intersects( geography geogA , geography geogB );```
is not.

**Comment by keithdoggett** [comment]
Closing since this is an issue with the `RGeo::Geographic.spherical_factory`. Although `centroid` has been added to it.
