### ISSUE TITLE
Document upgrading to 3.0

### ISSUE THREAD

**Issue by teeparham** [rgeo/activerecord-postgis-adapter#181]
- Use `SpatialFactoryStore` instead of `set_rgeo_factory_settings`
- `st_point` & `st_polygon`

**Comment by doomspork** [comment]
This would be awesome to have.  Just upgraded and it's been quite a bumpy road thus far.

**Comment by teeparham** [comment]
Here's documentation on `SpatialFactoryStore`: https://github.com/rgeo/rgeo-activerecord#spatial-factories-for-columns

**Comment by mjy** [comment]
@keithdoggett can be closed as done or wontfix.  Mention points to unclosed issue.
