### ISSUE TITLE
How to Configure Column Specific Factories

### ISSUE THREAD

**Issue by schmijos** [rgeo/activerecord-postgis-adapter#182]
Before version `3.0.0.beta5` of _activerecord-postgis-adapter_ we could configure default factories for spatial fields by column:

```
set_rgeo_factory_for_column(:some_column, some_factory)
```

 As of version `3.0.0.beta5` we can now configure an overall default for different spatial types and different _srid_'s:

```
factory_store = RGeo::ActiveRecord::SpatialFactoryStore.instance
factory_store.register(some_factory, geo_type: 'polygon', srid: 4326)
```

**Only for knowing the features:**
Is it still possible to configure a default factory for a column (without registering it for all the type/srid combinations)?

**Comment by teeparham** [comment]
You are correct. The answer to your question is technically "no". But there are ways to associate different spatial factories with the same column type (is that what you want to do?). See #163 for a discussion of possible solutions. 

Can you share specifically your problem?

**Comment by teeparham** [comment]
I wrote some more explanation here: https://github.com/rgeo/rgeo-activerecord#spatial-factories-for-columns

**Comment by mjy** [comment]
@keithdoggett close as answered.
