### ISSUE TITLE
Arel 6 - geographic changes to geometry in version 3

### ISSUE THREAD

**Issue by jaybloke** [rgeo/activerecord-postgis-adapter#183]
Not sure if this is a bug… or I'm simply not using v3 of the adapter correctly ( :-1: )

Before I was using Rails 4.2.1 with version 2.2.2 activerecord-postgis-adapter

```
latlng = RGeo::Geographic.spherical_factory(srid: 4326).point(121.0199964, 14.5380189)
Arel::Nodes::NamedFunction.new('ST_Distance', [latlng, latlng]).to_sql
```

This correctly gives me this SQL:

```
ST_Distance('0101000020E61000006A02FB9E47415E408242983677132D40', ‘0101000020E61000006A02FB9E47415E408242983677132D40')
```

After upgrading to Rails 4.2.1 w/activerecord-postgis-adapter 3 I tried the following:

```
latlng = RGeo::Geographic.spherical_factory(srid: 4326).point(121.0199964, 14.5380189)
Arel::Nodes::NamedFunction.new('ST_Distance', [latlng, latlng]).to_sql
```

But it gives me: RuntimeError: unsupported: RGeo::Geographic::SphericalPointImpl

However, 

```
Arel::Nodes::NamedFunction.new('ST_Distance', [latlng.as_text, latlng.as_text]).to_sql
```

Gives me this SQL:

```
ST_Distance(ST_GeomFromEWKT('POINT (121.0199964 14.5380189)'), ST_GeomFromEWKT('POINT (121.0199964 14.5380189)’))
```

Seems like all geography factories are being converted to geometry in Arel. The workaround is to cast to geography like so:

```
ST_Distance(Geography(ST_GeomFromEWKT('POINT (121.0280889 14.5491603)')), Geography(ST_GeomFromEWKT('POINT (121.0280889 14.5491603)')))
```

This works, but does seem somewhat longwinded. Any pointers or suggestions?

Thx

**Comment by jaybloke** [comment]
It looks like this goes deeper. I set up a basic app and followed the instructions on the readme page and tried this from the console:

~~~
 Arel::Nodes::NamedFunction.new('ANYTHING', ['param_1', 'param_2']).to_sql
~~~

And surprisingly got this: 

~~~
ANYTHING(ST_GeomFromEWKT('param_1'), ST_GeomFromEWKT('param_2'))
~~~

**Comment by zaidakram** [comment]
Yup, facing the same issue here...

```
Arel::Nodes::NamedFunction.new('ARRAY_LENGTH', ['participants', 1]).to_sql
```
results in 

```
ARRAY_LENGTH(ST_GeomFromEWKT('participants'), 1)
```

**Comment by bobbrez** [comment]
Also seeing it with:
`Arel::Nodes::InfixOperation.new "->", table[:values], 'foo`
resulting in
`"measurements"."values" -> ST_GeomFromEWKT('foo')`

**Comment by amenzhinsky** [comment]
The same thing.

I'm using ransack to query tables with custom arel filters

```ruby
Arel::Nodes::NamedFunction.new('concat_ws', [' ', parent.table[:first_name], parent.table[:last_name], parent.table[:middle_name]])
```
becomes
```
concat_ws(ST_GeomFromEWKT(' '), "drivers"."first_name", "drivers"."last_name", "drivers"."middle_name")
```

**Comment by 1dot44mb** [comment]
Did anyone find a solution for this?

**Comment by teeparham** [comment]
This is probably the place to start looking:

https://github.com/rgeo/activerecord-postgis-adapter/blob/master/lib/active_record/connection_adapters/postgis/arel_tosql.rb

**Comment by amenzhinsky** [comment]
First of all, rails 4 brings new Arel 6 which has a lot of api changes and old syntax won't work

```ruby
# rails < 4.2
Arel::Nodes::NamedFunction.new('ANYTHING', ['param_1', 'param_2'])

# rails >= 4.2
Arel::Nodes::NamedFunction.new('ANYTHING', [Arel::Nodes::Quoted.new('param_1'), Arel::Nodes::Quoted.new('param_2')])
```

[This commit](https://github.com/rails/arel/commit/93d72131bcc24ccb5536bec672d2dac94f8de651#diff-3538aead5b80677372eea0e903ff728eR587) dropped support for `visit_String` particularly and I don't know whether It has to be supported in postgis adapter or not.

**Comment by amenzhinsky** [comment]
`Arel::Nodes::Quoted` also works properly with spatial data

```ruby
Arel::Nodes::NamedFunction.new('ANYTHING', [Arel::Nodes::Quoted.new(coords)]).to_sql
# => "ANYTHING('002000000100000ec941479265cde6a904415b3c69575d59b3')"
```

**Comment by amenzhinsky** [comment]
@teeparham maybe it would be better to drop `visit_String` at all?

**Comment by dfurber** [comment]
For those who came here looking to get the custom name ransacker, here's what just worked for me:
`  ransacker :name, formatter: proc { |v| v.mb_chars.downcase.to_s } do |parent|
    Arel::Nodes::NamedFunction.new('LOWER',
                                   [Arel::Nodes::NamedFunction.new('concat_ws',
                                                                   [Arel::Nodes::Quoted.new(' '),
                                                                     Arel::Nodes::InfixOperation.new("->>", parent.table[:data], Arel::Nodes::Quoted.new('first_name')),
                                                                     Arel::Nodes::InfixOperation.new("->>", parent.table[:data], Arel::Nodes::Quoted.new('middle_name')),
                                                                     Arel::Nodes::InfixOperation.new("->>", parent.table[:data], Arel::Nodes::Quoted.new('last_name'))
                                                                     ])])
  end
`

**Comment by mauriciopasquier** [comment]
I got bit by this when trying to order a table with 2 quoted column names:

    key = ["\"some_id\"", "\"other_id\""]
    Arel::Table.new('some_table').order(key).to_sql

    => "SELECT FROM \"some_table\"  ORDER BY ST_GeomFromEWKT('\"some_id\"'), ST_GeomFromEWKT('\"other_id\"')"

Of course, [the file](https://github.com/rgeo/activerecord-postgis-adapter/blob/master/lib/active_record/connection_adapters/postgis/arel_tosql.rb) that @teeparham linked houses the culprit:

    def visit_String(node, collector)
      collector << "#{st_func('ST_WKTToSQL')}(#{quote(node)})"
    end

I don't know about Arel internals, but I tried some shotgun debugging, removing this `visit_String` method. Not surprisingly it gives `unsupported: String`. But the "no op" of passing the `node` unmodified to the `collector` works:

    def visit_String(node, collector)
      collector << node
    end

**Comment by kitsunde** [comment]
The issue is basically that the DB adapter doesn't have support for `visit_String`, but PostGIS is casually adding effectively a core feature into arel where previously only nodes are supported and it causes confusion.

I.e. instead of:

```ruby
>>> Arel::Nodes::Count.new(['*'])
COUNT(ST_GeomFromEWKT('*'))
```

You should be getting

```ruby
>>> Arel::Nodes::Count.new(['*'])
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: String. Construct an Arel node instead.
```

Because the proper way of constructing that Arel is

```ruby
Arel::Nodes::Count.new([Arel.star])
```

Or in a more general fashion

```ruby
Arel::Nodes::Count.new([Arel::Nodes::SqlLiteral.new('*')])
```

So basically the solution really is to remove `visit_String` since the adapter can work just fine without it using Arel in the standard fashion.

**Comment by keithdoggett** [comment]
Removing `visit_String` seems like it will be the fix. Before that can be done, some of the `rgeo-activerecord` `Arel` interface will likely have to be rewritten since it depends on `visit_String` (https://github.com/rgeo/rgeo-activerecord/blob/master/lib/rgeo/active_record/arel_spatial_queries.rb#L89).
