### ISSUE TITLE
NoMethodError using activerecord_postgis_adapter

### ISSUE THREAD

**Issue by oyeanuj** [rgeo/activerecord-postgis-adapter#185]
Apologies if this is very newbie question, but I have tried to solve it for a couple of days with zero luck.

I tried installing activerecord-postgis-adapter as per the README but am unable to create the model instance as I keep getting the error mentioned below on the code pasted below that.
NoMethodError: undefined method `set_rgeo_factory_for_column'

Here are what my different files look like:

Location.rb (the model)
```ruby
#self.rgeo_factory_generator = RGeo::Geos.factory_generator`
set_rgeo_factory_for_column(:coordinates,  RGeo::Geographic.spherical_factory(:srid => 4326) )
```

Console
```
irb(main):001:0> loc = Location.create
NoMethodError: undefined method 'set_rgeo_factory_for_column' for Location
```

Gemfile
```ruby
gem 'rgeo'
gem 'rgeo-activerecord'
gem 'activerecord-postgis-adapter'
```
config/application.rb
```ruby
require 'rails/all'
#require 'active_record/connection_adapters/postgis_adapter/railtie'
#require "#{Rails.root}/lib/rgeo"
```

config/database.yml
```ruby
development:
    <<: *default
    database: geoproject-api_development
    adapter: postgis
    schema_search_path: "public,postgis"
```

The lines of code commented above refer to the solutions I tried based on what was mentioned in various threads but didn't work for me.

I am using Rails 4.2.1.

Any help would be much appreciated!

**Comment by oyeanuj** [comment]
I did manage to fix that by finally understanding that I was using older syntax with the latest version of the adapter. 

I do have another follow-up question incase anybody else has run into this - 

    irb(main):003:0> lala = Location.first
    Location Load (1.6ms) SELECT "locations".* FROM "locations" ORDER BY "locations"."id" ASC LIMIT 1
    (Object doesn't support #inspect) 
    irb(main):004:0> lala.class.name => "Location" 
    irb(main):005:0> puts lala
    #<Location:0x007fdfd4bb2860>
    => nil
    irb(main):006:0> puts lala.inspect
    NoMethodError: undefined method point' for nil:NilClass

**Comment by AndreasHeiberg** [comment]
+1 I have the same issue #190

**Comment by AndreasHeiberg** [comment]
If you want the solution I fixed my issue, read through my explanation and see if it works for you.

**Comment by jlanio** [comment]
I 'm having the same problem.
please. 
            what was the solution?

**Comment by AndreasHeiberg** [comment]
For a potential solution look at #190

**Comment by jlanio** [comment]
I do not think that has to do with the lib.
after running the commands:
2.2.1 :001 > require 'rgeo'
 => true 
2.2.1 :002 > RGeo::Geos.supported?
 => true 
2.2.1 :003 >

**Comment by oyeanuj** [comment]
This finally solved it for me: http://stackoverflow.com/questions/30834862/nomethoderror-using-activerecord-postgis-adapter/30851483?noredirect=1#comment50175600_30851483.

Essentially, modifying rgeo initializer code to 
```ruby
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config| 
    config.default = RGeo::Geographic.spherical_factory(srid: 4326) 
end
```

**Comment by mylesboone** [comment]
Hi Anuj...can you tell me what the fix was for the original problem (set_rgeo_factory_for_column)? You say that the syntax changed in the newer version. Can you tell me where you found it? Thanks!

**Comment by teeparham** [comment]
The new `SpatialFactoryStore` class is documented here: https://github.com/rgeo/rgeo-activerecord#spatial-factories-for-columns

**Comment by mylesboone** [comment]
Got it - Thank you!

Date: Thu, 10 Mar 2016 08:29:06 -0800
