### ISSUE TITLE
undefined method `point' for nil:NilClass

### ISSUE THREAD

**Issue by AndreasHeiberg** [rgeo/activerecord-postgis-adapter#190]
# Problem
90% sure it's a setup error on my end, but I can't do self.factory and trying to access lonlat gives me an exception "undefined method `point' for nil:NilClass"

# I can
Set lonlat using:

```
mfactory = RGeo::ActiveRecord::SpatialFactoryStore.instance.factory(:geo_type => 'point')
self.lonlat = mfactory.point(long, lat)
self.save
```
This gives me values like `0101000020E610000061C3D32B65965DC03657CD7344F64040` in the db.

I can't use:

```
self.lonlat = "POINT(#{long},#{lat})"
self.save
```

# Questions
Do I need to setup something specific in the model?

**Comment by AndreasHeiberg** [comment]
I thought it might be my version of GEOS as I read https://github.com/rgeo/activerecord-postgis-adapter/issues/186

But I did install it with brew to no avail and then tried to run your test suite. The test suite works!

**Comment by AndreasHeiberg** [comment]
Found http://stackoverflow.com/questions/30834862/nomethoderror-using-activerecord-postgis-adapter

But I already have an initializer with the same code in it.

I tried adding locFactory = RGeo::ActiveRecord::SpatialFactoryStore.instance.factory(:geo_type => 'point')

But that didn't work.

A commenter suggested removing `config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")` that didn't work

**Comment by AndreasHeiberg** [comment]
Yes! I figured it out!

1 hint: [RGeo can't find support for Geos](https://coderwall.com/p/tzbc1w/rgeo-upgrade-to-0-3-20-in-rails-4-2-2-nomethoderror-undefined-method-point-for)

2 hint: `brew install geos` say's it's already installed

3 hint: `which geos-config` proves that I have it installed, so RGeo must be looking the wrong place for it

4 hint: [RGeo allows you to change the install path of Geos, although their docs incorrectly say Homebrew installed should work by default](https://github.com/rgeo/rgeo#installation)

5 hint: [There's an easy solution, install the rgeo gem with the right flags](https://github.com/rgeo/rgeo/issues/6)

```sh
$ /usr/local/bin/geos-config --prefix
/usr/local/Cellar/geos/3.4.2
$ gem install rgeo -- --with-geos-dir=/usr/local/Cellar/geos/3.4.2
```

**Comment by AndreasHeiberg** [comment]
http://stackoverflow.com/questions/31170055/activerecord-postgis-adapter-undefined-method-point-for-nilnilclass/31170056#31170056

**Comment by teeparham** [comment]
This should be fixed in rgeo by https://github.com/rgeo/rgeo/pull/126
