### ISSUE TITLE
JRuby - Geometry saved do DB as String

### ISSUE THREAD

**Issue by SvehlaJan** [rgeo/activerecord-postgis-adapter#211]
Hello.

I am trying to migrate my app to JRuby and I encountered problem with spatial data. In console (and in app) I can work with RGeo objects perfectly. `RGeo::Geos.supported?` returns true and everything seems fine. But when I save the geometry record, it is saved as String.
`...`
`if RGeo::Geos.supported?`
`point = RGeo::Geographic.spherical_factory(:srid => SRID).point(location_params[:lon], location_params[:lat])`
`current_user.geom = point`
`if current_user.save`
`...`

Gemfile:
`ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.16'`
`gem 'activerecord-postgis-adapter', platform: :jruby`
`gem 'activerecord-jdbcpostgresql-adapter', '~> 1.3.9', platform: :jruby`
`gem 'ffi-geos', platform: :jruby`

Migration:
`t.st_point :geom, geographic: true`

I checked using pgAdmin the column in DB and it's type is `geography`. I am not very experienced with Ruby and this problem maked me helpless.

Thank you for any advice.

PS: I was also transfering DB using pg_dump from old server so there might be problem.

**Comment by SvehlaJan** [comment]
Still no luck but I forgot to mention that whenever I execute JRuby (rake db:migrate, pumactl start), I get these warnings before execution:
`/home/dzony/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis_adapter.rb:33 warning: already initialized constant SPATIAL_COLUMN_OPTIONS`
`/home/dzony/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis_adapter.rb:48 warning: already initialized constant DEFAULT_SRID`

**Comment by jarblz** [comment]
I'm getting this exact issue.  Any luck with this?

Cheers,

Jared

**Comment by Sprachprofi** [comment]
In your database.yml, change the URL from postgres:// to postgis://

**Comment by keithdoggett** [comment]
Closing since the last comment appears to fix it.
