### ISSUE TITLE
NameError: uninitialized constant RGeo::CoordSys::SRSDatabase::ActiveRecordTable

### ISSUE THREAD

**Issue by jtgeibel** [rgeo/activerecord-postgis-adapter#217]
The ActiveRecordTable class providing SRS database support in postgis was removed from RGeo in commit rgeo/rgeo@b0363cb0f1.  The message there states that this functionality was moved to this gem, however I cannot find the equivalent functionality here.

Will this code still be migrated, or am I missing some new way that this can be accessed easily?

**Comment by mauriciopasquier** [comment]
Curious about this too. I'm currently updating an app to latest rgeo et al, in which I instantiated factories like this:

    RGeo::Geos.factory(
      srs_database: RGeo::CoordSys::SRSDatabase::ActiveRecordTable.new,
      srid:         some_srid
    )

I really don't want to use proj4 definitions explicitly. Is there any alternative?

**Comment by mauriciopasquier** [comment]
@teeparham sorry to ping you, but I guess you're the current maintainer. Maybe there is some rationale for leaving it out?

**Comment by keithdoggett** [comment]
Closing as stale/outdate. Please re-open if this is still an issue.
