### ISSUE TITLE
Error loading gem in test environment

### ISSUE THREAD

**Issue by zoras** [rgeo/activerecord-postgis-adapter#219]
In Gemfile
```[ruby]
gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'activerecord-postgis-adapter'
```

`activerecord-postgis-adapter` gem is working fine in development but errors out in test saying:
`There was an error while trying to load the gem 'activerecord-postgis-adapter'`
```[bash]
$ rspec spec
~/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activerecord-postgis-adapter'. (Bundler::GemRequireError)
from ~/code_repo/config/application.rb:18:in `<top (required)>'
```

Line 18 from application.rb
```[ruby]
Bundler.require(*Rails.groups)
```

**Comment by zoras** [comment]
There was a silly mistake on my part. I had a file named `rgeo.rb` inside Rails lib folder and it was being required instead of the `rgeo` file of `rgeo gem`. Renaming the file solved it.

**Comment by zoras** [comment]
There was a mistake on my part. I had a file named rgeo.rb inside Rails lib folder and it was being required instead of the rgeo file of rgeo gem. Renaming the file solved it.

**Comment by butchmarshall** [comment]
I'm also encountering this error but don't understand your solution.  What did you have to do?

**Comment by zoras** [comment]
@butchmarshall I renamed the `rgeo.rb` file inside Rails lib folder to `some_rgeo.rb`
