### ISSUE TITLE
schema's `id: :integer` preventing primary key sequences

### ISSUE THREAD

**Issue by jachenry** [rgeo/activerecord-postgis-adapter#224]
I'm currently making use of the postgis adapter for one of my projects and hit a strange issue when running `rake db:reset` last night. After running the command I noticed none of the primary keys had a auto incrementing sequence generated. I haven't found the code to prove it, but I believe rails is foregoing sequence creation if the id option is provided to a `create_table` call. Unfortunately for me, the postgis adapter appears to be adding this option as part of `db:schema:dump` leaving me the only option of find/replace if I ever want to make use of `db:schema:load`.

```
  create_table "models", id: :integer, force: :cascade do |t|
    t.string "name"
  end
```

Why is the postgis adapter including the `id` option? Is it possible to make the adapter smart enough to ignore this option in the case it is the default `id: :integer`?
## Stack

Ruby: 2.2.2p95
Rails: 5.0.0.rc1
activerecord-postgis-adapter: 4.0.0.beta4

**Comment by samphilipd** [comment]
We're seeing this even without the postgis adapter.

**Comment by keithdoggett** [comment]
Closing since I think this is an upstream error and likely outdated at this point.
