### ISSUE TITLE
unknown OID 19854: failed to recognize type of 'lnglat'. It will be treated as String.

### ISSUE THREAD

**Issue by TangMonk** [rgeo/activerecord-postgis-adapter#231]

**Comment by tibbon** [comment]
I'm getting similar errors.

**Comment by wildrhombus** [comment]
I am as well.  But only my my production database, so I'm wondering if it's a postgres version issue?

**Comment by teeparham** [comment]
Needs more info. Closing as stale. Please re-open if this is still an issue.
