### ISSUE TITLE
Rails 5.1 problems

### ISSUE THREAD

**Issue by MtnBiker** [rgeo/activerecord-postgis-adapter#248]
With no version specified `bundle update` resulted in `Installing activerecord-postgis-adapter 3.1.2 (was 4.0.2)`, but then `rails server` error 

    ~/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activerecord-postgis-adapter'. (Bundler::GemRequireError)
    Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition
    Did you mean?  ActiveRecord::ConnectionAdapters::ColumnDefinition
                   ActiveRecord::ConnectionAdapters::AddColumnDefinition
    Backtrace for gem load error is:
    ~/.gem/ruby/2.4.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:46:in `<module:PostGIS>'
...
Put version 4.0.2 in Gemfile and got this `bundle update` error

    Bundler could not find compatible versions for gem "activerecord":
      In Gemfile:
        activerecord-postgis-adapter (= 4.0.2) was resolved to 4.0.2, which depends on
          activerecord (~> 5.0.0)
    
        rails (~> 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
          activerecord (= 5.1.0.rc1)

**Comment by MtnBiker** [comment]
Why is it closed? Rails people say it doesn't support 5.1 based on https://github.com/rgeo/activerecord-postgis-adapter/blob/master/activerecord-postgis-adapter.gemspec#L22.

If I understand it that file needs to support activerecord 5.1.

**Comment by scottfromsf** [comment]
I agree with @MtnBiker, this seems like an issue that needs to be addressed here, not on the Rails project.

**Comment by MtnBiker** [comment]
@scotfromsf The Rails project agrees. https://github.com/rails/rails/issues/28551. Thank you for commenting.

**Comment by aomega08** [comment]
Definitely an issue here, I started digging into this, but honestly I'm not so well knowledgeable about the AR internals and I got lost in short. BTW the few edits I made on my local clone would not be backward compatible.

But having this before Rails 5.1 is out would be great.

**Comment by kofronpi** [comment]
Updating the rgeo-activerecord dependency to 5.1.0 would be a great start :+1:

**Comment by teeparham** [comment]
Fixed by #246
