### ISSUE TITLE
Issue with Rails' new `point` handling.

### ISSUE THREAD

**Issue by LeoAdamek** [rgeo/activerecord-postgis-adapter#249]
Rails 5.1 will change the default handling of `point` fields from an array of x and y coordinates, to use the `ActiveRecord::Point` type, with x and y members.

It is possible in Rails 5.0 to use this new behaviour already with the following:

````ruby
attribute :field_name, :point
````

However when using activerecord-postgis-adapter with this configuration, the following error occurs:

    ArgumentError: Unknown type :point
    from $RAILS_ROOT/app/vendor/ruby/2.3.0/gems/activemodel-
    5.0.1/lib/active_model/type/registry.rb:20:in `lookup'

Any ideas how this can be resolved?

**Comment by PelagicDev** [comment]
Just curious, but did you [see this section](https://github.com/rgeo/activerecord-postgis-adapter#point-and-polygon-types-with-activerecord-42) in the readme @LeoAdamek?
