### ISSUE TITLE
Understand Lat/Lon vs Lon/Lat

### ISSUE THREAD

**Issue by marcosanfilippo** [rgeo/activerecord-postgis-adapter#250]
I can't understand how this adapter handle coordinates, as Lat/Lon or Lon/Lat.

From original documentation: http://postgis.net/2013/08/18/tip_lon_lat/

*In mapping frameworks spatial coordinates are often in order of latitude and longitude. 
In spatial databases spatial coordinates are in x = longitude, and y = latitude.*

Now, how are treated in this adapter? 
Lon/Lat, as the same of the spatial databases? 
Or Lat/Lon? I can't find explicit references.

Thank you.

**Comment by teeparham** [comment]
Geographic coordinate values are returned in longitude, latitude order by PostGIS.
