### ISSUE TITLE
No longer compatible with rails < 5.1 but gemspec is not restricted to rails >= 5.1

### ISSUE THREAD

**Issue by tindron** [rgeo/activerecord-postgis-adapter#254]
activerecord-postgis-adapter is incompatible with arel < 8, but the gemspec does not prevent updating if you are on an earlier version.  The gem should probably be yanked and replaced with one that is restricted to arel 8 or rails 5.1 or above.

**Comment by teeparham** [comment]
Confirmed - thanks for reporting. I'll fix this in a few hours.

**Comment by teeparham** [comment]
Note: gem version 5.0.0 has been yanked. Version 5.0.1 is released.
