### ISSUE TITLE
ST_DWithin doesn't work in WHERE statement

### ISSUE THREAD

**Issue by marcosanfilippo** [rgeo/activerecord-postgis-adapter#256]
Hello everyone, I have the following problem:

I need to find all closest resources in a given radius.

The code is:

```
Resource.where("ST_DWithin(
          ST_GeographyFromText('POINT(? ?)'),
          ST_GeographyFromText(resource.lonlat.as_text),
          ?)",
          from[:lon], from[:lat], radius)
```

Please note the **resource.lonlat.as_text** that should give me a `POINT(X Y)`.

Error is:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "lonlat"
LINE 3: ...                             ST_GeographyFromText(resource.lonlat.as_text
```

If I put **resource.lonlat** instead of **resource.lonlat.as_text**, error is: (AS EXPECTED) 

`ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function st_geographyfromtext(geography) does not exist`

Because it returns a `RGeo::Geographic::SphericalPointImpl` but I need a `POINT(X Y)`

What is wrong? Why the `.SELECT()` allows me to use table name `resource` while the `.WHERE()` not?

I'm doing something wrong?

Thanks

**Comment by teeparham** [comment]
You need to interpolate that string `#{resource.lonlat.as_text}`
