### ISSUE TITLE
prefix `comment: ` ignoring

### ISSUE THREAD

**Issue by QNester** [rgeo/activerecord-postgis-adapter#269]
Hi.

Current version of gem not support commentaries for datbase.
I write:
```
create_table :constraints, comment: 'Constraints of application' do |t|
      t.string :title, comment: 'Title of constraint'
      t.timestamps
end
```

And `comment: ...` was ignored after migration. I can't see comments in schema.rb and in Datagrip.
AR 5.0.

**Comment by teeparham** [comment]
See #275
