### ISSUE TITLE
Size of the spatial_ref_sys table

### ISSUE THREAD

**Issue by oyeanuj** [rgeo/activerecord-postgis-adapter#273]
Hi @teeparham, I noticed that I had 5536 records in the `spatial_ref_sys` table. So, I was curious if that was indeed correct or a misconfiguration on my end or they were needed for specific use-cases? 

I only noticed now since I was on Heroku's free Postgres plan which allows 10K rows and was going over it. Turns out more than half of them are in this table, hence the question.

Thank you!

**Comment by teeparham** [comment]
That sounds right. The number of rows in the table may vary slightly depending on what version of PostGIS you are using. You do not need all the rows in that table - most are rare local projections. You can delete the ones you are not using.

For example, to keep only the 4 most common projections: 

`delete from spatial_ref_sys where srid not in (4326, 4269, 3395, 2163)`

https://postgis.net/docs/using_postgis_dbmanagement.html#spatial_ref_sys

```
psql=# \d spatial_ref_sys;
         Table "public.spatial_ref_sys"
  Column   |          Type           | Modifiers
-----------+-------------------------+-----------
 srid      | integer                 | not null
 auth_name | character varying(256)  |
 auth_srid | integer                 |
 srtext    | character varying(2048) |
 proj4text | character varying(2048) |
```

**Comment by oyeanuj** [comment]
Thank you @teeparham, that was very helpful!
