### ISSUE TITLE
PostGIS Installation pre-requisites

### ISSUE THREAD

**Issue by marielle-nec** [rgeo/activerecord-postgis-adapter#274]
It's not very clear that one needs to have post Postgres and PostGIS already installed on the users computer before following the steps to create or update a Rails project/database using the gem. Please consider adding this to prevent others from wasting a chunk of time figuring it out :)

**Comment by teeparham** [comment]
I agree it'd be nice to have set-up instructions for all the pre-requisites for all supported platforms.

Pull requests are welcome.

**Comment by keithdoggett** [comment]
Fixed by #334
