### ISSUE TITLE
Bug fixed: when using geometry with has_z

### ISSUE THREAD

**Issue by eliasbaixas** [rgeo/activerecord-postgis-adapter#280]
Hi,

in file 
activerecord-postgis-adapter-5.0.3/lib/active_record/connection_adapters/postgis/oid/spatial.rb

line 30, in parse_sql_type where it says:

if params.size > 1

it should be if params.size >= 1

because for example, I have a column without srid (bc I'm using cartesian space) , so the sql_type becomes:

geometry(PointZ) and since params.size == 1, the PointZ doesn't get parsed bc if params.size == 1 (not >1) and then has_z is left "false" and id doesnt parse PointZ(a b c).

fixed just by replacing >1 for >= 1

**Comment by teeparham** [comment]
Thanks for looking into this. Can you submit a PR with a test?
