### ISSUE TITLE
Unable to create an attribute for an array

### ISSUE THREAD

**Issue by volkanunsal** [rgeo/activerecord-postgis-adapter#284]
I'm unable to use the `array` option for attributes when using postgis adapter. I already created [an issue on Rails repo](https://github.com/rails/rails/issues/32324) about this, but I wonder if the solution might be found here.

Here is [the code](https://gist.github.com/volkanunsal/885983978ad2d25684a1e850f22ab188) to reproduce the issue.

**Comment by rockwellct** [comment]
I ran in to this recently as well, but based on the conversation in  https://github.com/rgeo/activerecord-postgis-adapter/issues/267, it seems you can solve it by adding an initializer that registers the types and modifiers

```
module ActiveRecord
  module ConnectionAdapters
    ActiveRecord::Type.register(
      :array,
      PostgreSQL::OID::Array,
      adapter: :postgis
    )

    ActiveRecord::Type.add_modifier(
      { array: true },
      PostgreSQL::OID::Array,
      adapter: :postgis
    )
  end
end
```

**Comment by dalton-cole** [comment]
Running into this on a new app after switching to the postgis adapter.

**Comment by keithdoggett** [comment]
With #334, the adapter will now check for types registered under the `:postgis` or `:postgresql` adapters.
