### ISSUE TITLE
Able to save a complex(self intersecting) polygon in the database using native queries but unable to access the geometry via rails console

### ISSUE THREAD

**Issue by Ume1931** [rgeo/activerecord-postgis-adapter#286]
I was able to save a complex self intersecting polygon into the database via postgresql console & the geometry was saved in the database but when i tried to retrieve the geometry via rails console it yields nil.

Accodring to OSGeos standards it should not be allowed to be saved in the database.But when it is saved in the database then why i am not allowed to retrieve it?

**Comment by teeparham** [comment]
rgeo/rgeo#183

**Comment by keithdoggett** [comment]
Closing since rgeo/rgeo#183 has been merged.
