### ISSUE TITLE
Upgrading to Rails 5.2 (Jruby)

### ISSUE THREAD

**Issue by SeanRoy** [rgeo/activerecord-postgis-adapter#290]
Our product was built in Rails 4 with Jruby and I'm trying to upgrade the database but running into a roadblock when I run db:migrate:
rake aborted!
Caused by:
Java::JavaSql::SQLException: No suitable driver found for jdbc:postgis://localhost...

I saw a note that the 5+ adapter does not yet support Jruby.  Does this mean I'm SOL, or is there a workaround?  Here's some more information about my stack

Rails 5.2
Postgis 2.2
Postgres 9.3.5
Sequel (sequel-rails) 

my postgres gems:
gem 'jdbc-postgres'
gem 'activerecord-jdbcpostgresql-adapter', github: 'jruby/activerecord-jdbc-adapter', platforms: [:jruby]
gem 'activerecord-postgis-adapter'
gem 'ffi-geos'

Any help or information would be greatly appreciated.  Thanks.

**Comment by keithdoggett** [comment]
Fixed with #332 #331 and #330
