### ISSUE TITLE
undefined method `property' for nil:NilClass

### ISSUE THREAD

**Issue by fabiancarlos** [rgeo/activerecord-postgis-adapter#297]
A alternative to everyone have a bug like that, because is using polygon:

`undefined method `property' for nil:NilClass`

First, do not use `st_polygon` or `st_point` to the column. Read the doc for they, and save the column like a string, and then uses `ST_GeomFromText(your_shape)` to transform it directly.
This only works if Postgis is configured correctly.

**Comment by 3zcurdia** [comment]
I got the same error but it only happens in production **(heroku)**, at first I thought it was the I missed the adapter but no, it is running on `postgis`. Any idea?

**Comment by 3zcurdia** [comment]
I found that the error is on the heroku buildpack https://github.com/cyberdelia/heroku-geo-buildpack/issues/51 cause RGeo is unsupported
```
irb(main):001:0> RGeo::Geos.supported?
=> false
```

**Comment by 3zcurdia** [comment]
yes it was the heroku buildpack, but I found a useful [article]( https://www.diowa.com/blog/heroku/2017/08/01/using-rgeo-with-geos-on-heroku-with-apt-get)

**Comment by mjy** [comment]
@keithdoggett Not an issue with adapter, can be closed?
