### ISSUE TITLE
Postgres Error when using Guard

### ISSUE THREAD

**Issue by OyoKooN** [rgeo/activerecord-postgis-adapter#31]
Hello,

I'm using guard to run my test suite but I get the following error since I added the gem and installed PostGIS, I get the following error.

```Exception encountered: #<ActiveRecord::StatementInvalid: PG::Error: ERROR:  must be owner of relation spatial_ref_sys: ALTER TABLE "spatial_ref_sys" ENABLE TRIGGER ALL>```

I'm not sure if it related to your gem but I prefer to report it to you.

**Comment by teeparham** [comment]
This is not a problem with this adapter. Closing.
