### ISSUE TITLE
Create ActiveRecord migration to enable postgis extension (if app is on Rails)

### ISSUE THREAD

**Issue by robinboening** [rgeo/activerecord-postgis-adapter#313]
Hey 👋 

I'd like to suggest a feature to make the extension enabling process a bit more transparent.

Today we had an issue in our Rails application where a `CREATE EXTENSION` statement in the schema went missing within a PR. This issue is unrelated to postgis, byt we were confused so we checked our migrations to see what extensions we enabled. I got even more confused when I noticed that `postgis` wasn't even enabled by us, until my colleague pointed me to this gem and I found the `PostgisDatabaseTasks` enabling it when called by a rake task.

I'd like to suggest to not directly enable the extension by calling a rake task, but instead creating a migration file in which its handled. Of course, only if `Rails` is available. It makes it transparent.

Thanks for all your awesome work! 👌

**Comment by seuros** [comment]
This rake task is legacy. it was implemented when rails did not have the ability to create extensions except by sql.

@keithdoggett i can push changes to remove it in V8.0.0 (as we cannot drop it for the current version)

**Comment by woodardj** [comment]
If I'm reading this (and several other issues) right, the `rails db:gis:setup` script should not be used anymore, is that accurate? The Readme.md at the project root still lists it as an installation step.

**Comment by woodardj** [comment]
Awesome, thanks @keithdoggett, makes sense. I ran into some weird connection errors when running that script against my Rails 6.1 + Postgres 13 project; I was about to file an issue for it, but I won't waste your time if that's not the future. (I was able to get up and running by writing a migration by hand)

**Comment by seuros** [comment]
I removed the rake task and updated the README in #353. I think having the migration embedded will be an overkill , since this gem will need be a rails engine.

**Comment by tindron** [comment]
> I removed the rake task and updated the README in #353. I think having the migration embedded will be an overkill , since this gem will need be a rails engine.

What do you think of adding this to History.md for 8.0 as a breaking change?  It was a little surprising to have my CI tests break after the upgrade due to not having the migration.

**Comment by keithdoggett** [comment]
Added documentation around this in this History file and the README #368
