### ISSUE TITLE
Unique indexing using gist access method

### ISSUE THREAD

**Issue by sepowitz** [rgeo/activerecord-postgis-adapter#314]
Firstly, thanks for all your hard work on this wonderful adapter. 

I am trying to create a unique index constraint using postGIS compatible fields, but am getting an error that the `PG::FeatureNotSupported: ERROR:  access method "gist" does not support unique indexes`. Is there a good work around for this?

Here's is a quick look at my migration:

```
class CreatePlots < ActiveRecord::Migration[6.0]
  def change
    create_table :plots, id: :uuid do |t|
      t.polygon :coordinates, null: false
      t.integer :variant_year, null: false

      t.timestamps
    end

    add_index :plots, [:coordinates, :variant_year], using: :gist, unique: true
  end
end
```

Any help would be much appreciated, thank you!

**Comment by mjy** [comment]
Can you add the constraint to a `before_validation` in Rails?

**Comment by sepowitz** [comment]
> Can you add the constraint to a `before_validation` in Rails?

I have a validation at the model level, but was hoping to add a constraint to the DB as well (in case of any race conditions). Was mostly curious if there is a way to support this using this adapter.

**Comment by keithdoggett** [comment]
It doesn't seem like this is possible with GIST in general but in the past, I've done something like this. https://gis.stackexchange.com/questions/314662/postgis-unique-constraint-for-spatial-equality

Where I've written a custom `check` function then added a constraint in the migration based on that. It's not too hard to do if you really need to have a DB level constraint.

**Comment by keithdoggett** [comment]
Closing since this is unrelated to the adapter.
