### ISSUE TITLE
pg_dump segmentation fault after pg_dump upgrade (-> 13)

### ISSUE THREAD

**Issue by lubosch** [rgeo/activerecord-postgis-adapter#321]
Mac OS, brew pg_dump -V -> 13
rake db:structure:dump uses pg_dump.

pg_dump started throwing segmentation fault after ugpradeing to 13. Problem is excluding spatial_ref_sys:

```
        ::ActiveRecord::SchemaDumper.ignore_tables |= %w(
          geography_columns
          geometry_columns
          layer
          raster_columns
          raster_overviews
          spatial_ref_sys
          topology
        )
```

this fixed the issue: ::ActiveRecord::SchemaDumper.ignore_tables -= %w[spatial_ref_sys]

some maybe related info: https://www.postgresql-archive.org/BUG-16655-pg-dump-segfault-when-excluding-postgis-table-td6156885.html

**Comment by keithdoggett** [comment]
Thanks for submitting this. Do you know if this is still an error in 13.1? A fix for this bug may have been released with that version.

**Comment by keithdoggett** [comment]
Closing since this was an upstream issue and appears to be fixed. Please re-open if not.
