### ISSUE TITLE
NameError: undefined local variable or method `configuration' for PostGISDatabaseTasks

### ISSUE THREAD

**Issue by tagliala** [rgeo/activerecord-postgis-adapter#322]
Apologies if it is a duplicate, I've searched for "name error", `configuration`, and `hash_configuration`. I've also checked latest issues, PRs and tested master branch

When running specs against Rails 6.1, I'm getting:

```
NameError: undefined local variable or method `configuration' for #<ActiveRecord::ConnectionAdapters::PostGIS::PostGISDatabaseTasks:0x00007fadf0e921e0>
Did you mean?  configuration_hash
```

I think it may depend by rails/rails#37291

**Comment by javierjulio** [comment]
Same here. I was trying to update an app to Rails 6.1 and when running the test suite this error occurs.

**Comment by tagliala** [comment]
Hi @javierjulio I'm using `ar61` branch which contains AR61 support and specs in my application are all green

We just need to wait for 7.0.0 to be released to go back to the stable gem

**Comment by javierjulio** [comment]
@tagliala good to know, thank you!
