### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition in Rails 7

### ISSUE THREAD

**Issue by sokmesakhiev** [rgeo/activerecord-postgis-adapter#357]
Having an issue with Rails 7 
/Users/mac/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:46:in `<module:PostGIS>': uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition (NameError)
Did you mean?  ActiveRecord::ConnectionAdapters::ColumnDefinition
                           ActiveRecord::ConnectionAdapters::AddColumnDefinition

**Comment by keithdoggett** [comment]
We just released version 8 which is ActiveRecord compatible. Please try that and let me know if the issue persists.

**Comment by keithdoggett** [comment]
Closing, but if this is still an issue in the newest version please let me know

**Comment by asmrtfm** [comment]
Running on Ubuntu 22.04, Ruby 3.3.3, Rails 7.2.1 (asdf)
postgresql, postgis, and postgresql-14-postgis-3 installed through apt.

Following along with instructions in README...

> `rails generate migration AddPostgisExtensionToDatabase`
```
/home/me/.bundle/ruby/3.3.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:46:in `<module:PostGIS>': uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition (NameError)

      class ColumnDefinition < PostgreSQL::ColumnDefinition
                                         ^^^^^^^^^^^^^^^^^^
Did you mean?  ActiveRecord::ConnectionAdapters::AddColumnDefinition
	from /home/me/.bundle/ruby/3.3.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:3:in `<module:ConnectionAdapters>'
	from /home/me/.bundle/ruby/3.3.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:2:in `<module:ActiveRecord>'

...
```
