### ISSUE TITLE
heroku postgres error: permission denied for table spatial_ref_sys.

### ISSUE THREAD

**Issue by feynmanish** [rgeo/activerecord-postgis-adapter#362]
I am trying to delete a table which is not owned by the current_user.

I can't do it as current_user since I don't own the table; I can't create the postgis extension which produces the table as current_user on heroku. I can't grant privileges to current_user on hobby-tier. And it seems I can't change my role to user postgres. Is there a way?

**Comment by keithdoggett** [comment]
Does this wiki or the linked issue help? https://github.com/rgeo/activerecord-postgis-adapter/wiki/Heroku

I'm not very familiar with Heroku so I'm not much help if it is a Heroku specific issue, but I can try to help walk you through it and see if there's an issue with the adapter.
