### ISSUE TITLE
Where is the distance query?

### ISSUE THREAD

**Issue by MadBomber** [rgeo/activerecord-postgis-adapter#386]
I took a quick look through the README hoping to find an example AR query which showed me how to use this adapter and PostGIS to query something like:

Store.where location is < 10.miles away from Customer.location

given that location in both the stores and customers tables is a point object.

In ordinary PostgreSQL with the earth extension I can take two fields (lat, long) turn them into a point and in SQL query for the records having the shortest distance between two points... or all records within X miles of a point.

but that is SQL.  I'd rather see that hidden within the adapter.

Store.within(x).miles_of(:customers, :location)

**Comment by keithdoggett** [comment]
@MadBomber currently there are no high level scopes that you can use for spatial queries although some work has been started on that. For now you can use an Arel interface to access spatial queries in activerecord. See this example from the rgeo-activerecord gem (https://github.com/rgeo/rgeo-activerecord#spatial-queries).
