### ISSUE TITLE
Using the Adapter in Rails 7, Ruby 3.1.2, results in query times increasing 100%

### ISSUE THREAD

**Issue by cscherban** [rgeo/activerecord-postgis-adapter#391]
We recently started using the postgis adapter in a high-usage environment.

We noticed a significant jump in query latencies for general queries (non-geo, read and write). Reverting back to the postgresql adapter fixed our latency. 

Looking at the database level we saw that there was no change in db read and write latencies (using a cloud hosted Postgres database). 

Any help would be much appreciated, I'm not sure how further investigate this.

**Comment by BuonOmo** [comment]
@cscherban I would use a tool to monitor where the performance hit is (e.g: in ruby? in the db?). If it is in production you could use a monitor like new relic. If you are lucky enough to reproduce the issue locally, it will be even easier to pinpoint the issue with a profiler such as stackprof. These bits of information will help us drastically giving you guidance :)

**Comment by BuonOmo** [comment]
@cscherban any chance you found the culprit ?

**Comment by seuros** [comment]
This issue is stale. we should close it.
