### ISSUE TITLE
Create 9.0.2 release

### ISSUE THREAD

**Issue by eikes** [rgeo/activerecord-postgis-adapter#394]
After the "Add the ConnectionHandling module" commit (d05adc6ed6677aabbfdfe9c2e28fd0ba6cb834a0) was merged, the `rails dbconsole` command still fails (`Unknown command-line client for database_name`) unless you install this gem directly from the main branch from github. If a new release was available through ruby gems, this would be resolved. Any chance we can get this released?

**Comment by BuonOmo** [comment]
I won't be so available that I can do it before 1 month. Maybe @keithdoggett can?

Also we're volunteers (unpaid) and we cannot plan releases due to our other schedules on other projects. I'm closing the issue. You can still pinpoint the precise commit you want in your gemfile !

**Comment by keithdoggett** [comment]
Hey @eikes I can release that version this weekend

**Comment by keithdoggett** [comment]
@eikes 9.0.2 was just released

**Comment by eikes** [comment]
Many thanks!
