### ISSUE TITLE
This needs an updated dependency to rgeo-activerecord 8.0

### ISSUE THREAD

**Issue by Empact** [rgeo/activerecord-postgis-adapter#409]
As rgeo-activerecord 8.0 [tests against](https://github.com/rgeo/rgeo-activerecord/commit/d17e838129ec17283b03d77882ac46223340489f) ActiveRecord 7.2 to prove support, which this library currently targets as per: #397

Currently having master head installed prevents the upgrade to rgeo-activerecord 8.0.

**Comment by BuonOmo** [comment]
See #407 and #405. For now you have to target the `bump-7-2` branch if you aim for 7.2
