### ISSUE TITLE
Error: uninitialized constant RGeo::ActiveRecord::SpatialToSql (NameError) after upgarding to newly released version 10

### ISSUE THREAD

**Issue by upendra-azad** [rgeo/activerecord-postgis-adapter#416]
-- with rails 7.2

rails c
****/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-postgis-adapter-10.0.0/lib/active_record/connection_adapters/postgis/arel_tosql.rb:19:in `<top (required)>': uninitialized constant RGeo::ActiveRecord::SpatialToSql (NameError)

RGeo::ActiveRecord::SpatialToSql.prepend RGeo::ActiveRecord::SpatialToPostGISSql
                  ^^^^^^^^^^^^^^
Did you mean?  RGeo::ActiveRecord::SpatialToPostGISSql

**Comment by upendra-azad** [comment]
require_relative 'boot'
require 'rails/all'
require 'active_record/connection_adapters/postgis_adapter'
Bundler.require(*Rails.groups)

in my application.rb file these modules were being included.

adding require 'rgeo/active_record' in there fixed the issue.
earlier it didn't need to require this.

**Comment by BuonOmo** [comment]
I think this is related to https://github.com/rgeo/activerecord-postgis-adapter/pull/414 then!

**Comment by shamil** [comment]
@upendra-azad I've the same issue.

Even after adding ` require 'rgeo/active_record'` id didn't help.
I'm not using rails directly. Here is my code

```
require "bundler/setup"
require "active_support/all"
require "active_record"
```

**Comment by tindron** [comment]
Is there a workaround for this? The issue is closed, but it's still happening.
