### ISSUE TITLE
Release v10 update to fully support Rails 7.2

### ISSUE THREAD

**Issue by JamesChevalier** [rgeo/activerecord-postgis-adapter#420]
A release of e.g. 10.0.1 that includes https://github.com/rgeo/activerecord-postgis-adapter/pull/417 would make it fully compatible with Rails 7.2.
In the meantime, I can work around the issue of this not being available by using [my own fork](http://github.com/JamesChevalier/activerecord-postgis-adapter).

Also, https://github.com/rgeo/activerecord-postgis-adapter/issues/402 can be closed.

**Comment by keithdoggett** [comment]
Hey @JamesChevalier yes want to get this released soon. Waiting on this PR https://github.com/rgeo/activerecord-postgis-adapter/pull/418 first but hopefully tomorrow can merge and make a release

**Comment by keithdoggett** [comment]
10.0.1 has been released
