### ISSUE TITLE
20 km shift with SRID 32188

### ISSUE THREAD

**Issue by kaligrafy** [rgeo/activerecord-postgis-adapter#50]
Hi!

I tried to convert a lat/lon geographic geometry to MTM8 (SRID 32188) and I get a 20km shift (almost 20000 meters too high) for the y, but the x is correct.

If I use directly the postgis function ST_Transform, there is no shift.

Here is the rgeo command I use to transform (the one that shifts 20km):
RGeo::Feature.cast(geometry_attribute, :factory => RGeo::Cartesian.factory(:srs_database => RGeo::CoordSys::SRSDatabase::ActiveRecordTable.new, :srid => 32188), :project => true)

Thanks for any cue!

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
