### ISSUE TITLE
shp2pgsql cannot find postgis functions when using postgis schema

### ISSUE THREAD

**Issue by whyvez** [rgeo/activerecord-postgis-adapter#56]
I have setup my environment as per documentation and added postgis to schema_search_path. When I try to load data using shp2pgsql i get an error saying that the addGeometryColumn postgis function cannot be found. I gather its because the function its in a different schema than public. Is there a solution to this issue?

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
