### ISSUE TITLE
Rails 4 db:migrate broken - undefined method `non_geographic_spatial_columns'

### ISSUE THREAD

**Issue by slbug** [rgeo/activerecord-postgis-adapter#59]
<pre>
$ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
==  CreatePostgisExtensions: migrating ========================================
-- execute("CREATE EXTENSION postgis;")
   -> 1.0280s
-- execute("CREATE EXTENSION postgis_topology;")
   -> 0.5671s
==  CreatePostgisExtensions: migrated (1.5953s) ===============================

==  CreateCountries: migrating ================================================
-- create_table(:countries)
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `non_geographic_spatial_columns' for ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition:0x007f02724f6a48~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rgeo-activerecord-0.5.0/lib/rgeo/active_record/common_adapter_elements.rb:107:in `method_missing'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/activerecord-postgis-adapter-77bef269ffe3/lib/active_record/connection_adapters/postgis_adapter/rails4/main_adapter.rb:204:in `create_table'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:622:in `block in method_missing'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:594:in `block in say_with_time'
~/.rvm/rubies/ruby-2.0.0-p0-perf/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:594:in `say_with_time'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:614:in `method_missing'
~/work/geo_test/db/migrate/20130327124031_create_countries.rb:3:in `change'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:568:in `exec_migration'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:552:in `block (2 levels) in migrate'
~/.rvm/rubies/ruby-2.0.0-p0-perf/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:551:in `block in migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:302:in `with_connection'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:550:in `migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:702:in `migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:896:in `block (2 levels) in migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:976:in `block in ddl_transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/transactions.rb:209:in `transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:976:in `ddl_transaction'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:895:in `block in migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:891:in `each'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:891:in `migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:747:in `up'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/migration.rb:725:in `migrate'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bundler/gems/rails-30fbbb4ce378/activerecord/lib/active_record/railties/databases.rake:48:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
~/.rvm/rubies/ruby-2.0.0-p0-perf/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bin/rake:23:in `load'
~/.rvm/gems/ruby-2.0.0-p0-perf@cta/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate

</pre>

**Comment by ddd1600** [comment]
make sure your `adapter` is set to `postgis` in `config/database.yml`
