### ISSUE TITLE
Any tables with an index complain it "Could not dump table" in schema.rb

### ISSUE THREAD

**Issue by joshstewart** [rgeo/activerecord-postgis-adapter#61]
After adding in activerecord-postgis-adapter gem and running `rake db:gis:setup` and `rake db:migrate` schema.rb complains that it couldn't dump the table, even though the tables with the indexes have no spatial or geographic columns or indexes. See the error below in db/schema.rb.

```
# Could not dump table "my_table_name" because of following NoMethodError
# undefined method `using' for #<RGeo::ActiveRecord::SpatialIndexDefinition:0x007f8e6e77ce38>
```

**Comment by jarblz** [comment]
any updates on this? I'm getting an issue where when I run the migration adding my geometry column, I get a warning: "unknown OID 78913: failed to recognize type of 'polygon'. It will be treated as String.".  Also when I look at the schema file, my table to which i tried to add the geometry column is gone and the 'cannot dump table' error is in its place.  although the table still exists in my schema
