### ISSUE TITLE
Spork/Guard with Postgis

### ISSUE THREAD

**Issue by jorgedavila25** [rgeo/activerecord-postgis-adapter#63]
We're using the Postgis adapter, and I'm trying to setup Guard and Spork to speed up our time spent running tests. Our test pass flawlessly when not using the Spork server, but once we run it on the Spork server, we get an exception. 

```
NoMethodError:
undefined method `point' for #<Proc:0x007ff23e9697f8>
```

This exception is being thrown by this line of code: 

`self.coords = self.class.rgeo_factory_generator.point(geo.last, geo.first)`

**Comment by daqo** [comment]
I had a similar issue. You can find my workaround here: http://masl.cis.gvsu.edu/2015/02/19/rgeo-problem-on-production-environment-lat-and-lon-vanishes/

**Comment by phlegx** [comment]
I experienced the exact same problem when running in production. In development all works fine!

**Comment by bbradbury** [comment]
I have this problem in RAILS_ENV=test

**Comment by yfractal** [comment]
Have you guys forgot set ` adapter: postgis ` in "database.yml".

My problem caused by it...  :(

**Comment by vyachkonovalov** [comment]
I figure out that
```ruby
    Point.rgeo_factory_for_column(:location) # returns Proc
    Point.rgeo_factory_for_column(:location, {}).point(1,2) # returns nil
```
RAILS_ENV=production
rails 4.2.0, unicorn 4.8.3, unicorn-rails 2.2.0, activerecord-postgis-adapter 3.0.0.beta4

But if I run WEBrick, everything works like in development environment.
So, I tried to config unicorn and
```ruby
    # config/unicorn.rb
    preload_app false # was true
```
did the trick.

**Comment by teeparham** [comment]
This code no longer exists. Closing as stale. Please re-open if this is still an issue.
