### ISSUE TITLE
`geographic: true` doesn't force SRID 4326

### ISSUE THREAD

**Issue by marnen** [rgeo/activerecord-postgis-adapter#75]
Despite what the docs say, `geographic: true` doesn't force the SRID to be set to 4326. (I'm using Postgres.app [so PGSQL 9.2] with Rails 3.0 and Ruby 1.9.2 on Mac OS X 10.8.)

**Comment by murilosardinha** [comment]
+1

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue with rails 4.2+.
