### ISSUE TITLE
Marshal.dump on a GIS-enabled model raises TypeError

### ISSUE THREAD

**Issue by keichan34** [rgeo/activerecord-postgis-adapter#80]
```
TypeError (no _dump_data is defined for class Method)
```

Steps to reproduce:

```
object = SomethingSpatial.find(1)
Marshal.dump object
```

Rails 4.0.0
ActiveRecord 4.0.0
RGeo 0.3.20
activerecord-postgis-adapter 0.6.5

Can anyone else reproduce this error? Rails uses `Marshal` to dump objects into the cache, which means that no spatially-enabled objects can be cached right now...

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
