### ISSUE TITLE
rake db:test:prepare fails in Rails 4

### ISSUE THREAD

**Issue by petergoldstein** [rgeo/activerecord-postgis-adapter#83]
I'm seeing a fatal error when I run rake db:test:prepare after upgrading to Rails 4.  This is the error:

    ** Execute db:test:purge
    rake aborted!
    PG::DuplicateObject: ERROR:  type "spheroid" already exists

The error seems to occur because the postgis.sql script is being run twice, and the CREATE TYPE spheroid statement in the file cannot be safely run twice.

**Comment by teeparham** [comment]
This should be fixed in version `2.2` and later. Closing as stale.
