### ISSUE TITLE
Problem with eager_load = true

### ISSUE THREAD

**Issue by tobstarr** [rgeo/activerecord-postgis-adapter#86]
Does anybody experience any issues with `eager_load` being set to true when deploying unicorn with preload_app or puma (with the vanilla settings)?

We run into similar issues as described in https://github.com/dazuma/activerecord-postgis-adapter/issues/14#issuecomment-15647990 with `eager_load` being true and we do not have issues when disabling the setting.

Is there a workaround to enable `eager_load` but NOT break the postgis adapter?

**Comment by jmoe** [comment]
I have encountered this. Been a while, but was there ever any fix?

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
