### ISSUE TITLE
dump is missing :has_m => true

### ISSUE THREAD

**Issue by tompesman** [rgeo/activerecord-postgis-adapter#88]
I've table containing a geometry column generated by this piece of sql:

```
SELECT AddGeometryColumn('','table_name_here','geom','28992','POINT',4);
```

When I run `rake db:schema:dump` the `schema.rb` contains:

```
t.spatial "geom",       limit: {:srid=>28992, :type=>"point", :has_z=>true}
```

and is missing the :has_m => true. Maybe this is related to the fact that I had to manually include this line in my model to let the `geom` not to be `nil`.

```
set_rgeo_factory_for_column(:geom, RGeo::Cartesian.factory(:srid => 28992, :has_z_coordinate => true, :has_m_coordinate => true))
```

Is this the expected behaviour? All my other tables containing geo information 'just work'.

Thanks!

**Comment by workmaster2n** [comment]
I'm noticing the same thing with `has_z`

**Comment by teeparham** [comment]
Closing as stale. Please re-open if this is still an issue.
